#name: David Greenberg
#Project: Lab 2

test:
	gcc ./tube.c -g -o tube.out && ./tube.out  /usr/bin/cat ./testdoc.txt , /usr/bin/head -2

test2:
	gcc ./tube.c -g -o tube.out && ./tube.out /bin/cat filename , /bin/head -2 

test3:
	gcc ./tube.c -g -o tube.out && ./tube.out "/bin/ls" -l , "head" -2 
test4: 
	gcc ./tube.c -g -o tube.out && ./tube.out "/bin/ls" -l , "head" -2

