#name: David Greenberg
#Project: Lab 2

test:
	gcc ./tube.c -g -o tube.out && ./tube.out  /bin/cat ./testdoc.txt , head

test3:
	gcc ./tube.c -g -o tube.out && ./tube.out /bin/ls -l , /bin/head 
test4: 
	gcc ./tube.c -g -o tube.out && ./tube.out /bin/cat ./tube.c , /bin/wc

test5: 
	gcc ./tube.c -g -o tube.out && ./tube.out head , /bin/ls -l

